
sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - ng build --prod

deploy:
  provider: firebase
  token:
    secure: "FIREBASE_TOKEN"
  project: "event-viewer"